[platformio]
default_envs = teensy35

[env:teensy35]
platform = teensy
board = teensy35
framework = arduino
build_type = release
build_unflags = -std=gnu++11
build_flags =
  -D USB_SERIAL
  -std=gnu++17
  -O2
  -fno-exceptions
  -fno-rtti
  -fno-threadsafe-statics
  -Wall
monitor_speed = 115200
