M48
; DRILL file KiCad 10.0.5-10.0.5~ubuntu24.04.1 date 2026-08-04T18:33:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-04T18:33:53-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5-10.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
%
G90
G05
T1
X33.06Y-112.9
X38.14Y-111.884
X38.14Y-113.916
M30
